In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset = pd.read_csv('/content/datasets_596958_1073629_Placement_Data_Full_Class.csv')

In [ ]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
dataset['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [ ]:
x = dataset.iloc[: , 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
x

array([[ 0.7  ,  0.   ,  1.9  , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 0.88 ,  0.   ,  2.6  , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 0.76 ,  0.04 ,  2.3  , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 0.51 ,  0.13 ,  2.3  , ...,  3.42 ,  0.75 , 11.   ],
       [ 0.645,  0.12 ,  2.   , ...,  3.57 ,  0.71 , 10.2  ],
       [ 0.31 ,  0.47 ,  3.6  , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
y

array([5, 5, 5, ..., 6, 5, 6])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [ ]:
l_cla.fit(x_train, y_train)
k_cla.fit(x_train, y_train)
d_cla.fit(x_train, y_train)
r_cla.fit(x_train, y_train)
s_cla.fit(x_train, y_train)
ks_cla.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
l_pred = l_cla.predict(x_test)
k_pred = k_cla.predict(x_test)
d_pred = d_cla.predict(x_test)
r_pred = r_cla.predict(x_test)
s_pred = s_cla.predict(x_test)
ks_pred = ks_cla.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [ ]:
l_c

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,   9,   1,   0,   0],
       [  0,   0, 103,  27,   2,   0],
       [  0,   0,  51,  88,   6,   0],
       [  0,   0,   0,  17,  11,   0],
       [  0,   0,   0,   3,   0,   0]])

In [ ]:
k_c

array([[ 0,  1,  1,  0,  0,  0],
       [ 0,  0,  6,  4,  0,  0],
       [ 0,  1, 99, 29,  3,  0],
       [ 0,  1, 53, 79, 12,  0],
       [ 0,  0,  2, 15, 11,  0],
       [ 0,  0,  0,  2,  1,  0]])

In [ ]:
d_c

array([[ 0,  0,  2,  0,  0,  0],
       [ 0,  0,  4,  5,  1,  0],
       [ 2,  6, 95, 23,  6,  0],
       [ 2,  1, 35, 87, 18,  2],
       [ 0,  0,  3, 10, 14,  1],
       [ 0,  0,  0,  1,  1,  1]])

In [ ]:
r_c

array([[  0,   0,   1,   1,   0,   0],
       [  0,   0,   7,   3,   0,   0],
       [  0,   0, 108,  22,   2,   0],
       [  0,   1,  31, 100,  13,   0],
       [  0,   0,   1,  13,  13,   1],
       [  0,   0,   0,   1,   1,   1]])

In [ ]:
s_c

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,   9,   1,   0,   0],
       [  0,   0, 101,  31,   0,   0],
       [  0,   0,  53,  92,   0,   0],
       [  0,   0,   0,  28,   0,   0],
       [  0,   0,   0,   3,   0,   0]])

In [ ]:
ks_c

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,   9,   1,   0,   0],
       [  0,   0, 100,  32,   0,   0],
       [  0,   0,  45,  96,   4,   0],
       [  0,   0,   0,  18,  10,   0],
       [  0,   0,   0,   3,   0,   0]])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [ ]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.63125
KNN: 0.590625
Decision Tree: 0.615625
Random Forest: 0.69375
Linear SVC: 0.603125
Kernel SVC: 0.63125
