#Data Preprocessing

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red (3).csv')

In [ ]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [ ]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

#Separate Features and Target

* Here lets considering 'quality' as target
*  and rest of the columns as features

In [ ]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

In [ ]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
y

array([5, 5, 5, ..., 6, 5, 6])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
y_train

array([6, 7, 6, ..., 5, 6, 5])

In [ ]:
y_test

array([5, 5, 5, 5, 6, 6, 6, 6, 7, 5, 6, 5, 6, 6, 6, 6, 7, 5, 6, 6, 6, 6,
       4, 6, 5, 7, 6, 7, 6, 6, 5, 7, 7, 5, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6,
       6, 5, 5, 6, 5, 5, 7, 6, 5, 6, 6, 6, 5, 5, 7, 5, 5, 5, 6, 7, 7, 5,
       4, 5, 6, 5, 7, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 7, 5, 6, 7, 6, 6, 6,
       6, 7, 6, 6, 6, 5, 7, 6, 6, 6, 7, 5, 5, 6, 6, 6, 6, 7, 7, 5, 4, 8,
       6, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 7, 5, 5,
       5, 7, 7, 5, 4, 5, 5, 7, 5, 6, 6, 6, 5, 6, 8, 7, 6, 7, 5, 5, 7, 5,
       5, 7, 6, 5, 6, 6, 5, 5, 5, 7, 6, 6, 7, 4, 5, 6, 6, 7, 5, 4, 5, 7,
       7, 6, 5, 5, 5, 5, 5, 5, 5, 7, 6, 6, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5,
       7, 6, 6, 6, 5, 6, 5, 8, 5, 6, 5, 8, 5, 5, 6, 5, 5, 3, 5, 5, 6, 6,
       5, 4, 5, 5, 6, 6, 5, 6, 5, 5, 7, 5, 6, 5, 6, 6, 5, 5, 7, 5, 6, 5,
       5, 6, 7, 7, 5, 5, 6, 6, 6, 6, 6, 6, 7, 5, 6, 7, 5, 6, 6, 6, 4, 5,
       5, 6, 6, 5, 5, 5, 4, 5, 6, 5, 5, 6, 5, 5, 6, 6, 6, 7, 5, 7, 6, 6,
       7, 5, 5, 6, 6, 7, 7, 4, 4, 6, 6, 5, 4, 7, 6,

In [ ]:
x_train

array([[ 4.7  ,  0.6  ,  0.17 , ...,  3.85 ,  0.6  , 12.9  ],
       [ 7.4  ,  0.635,  0.1  , ...,  3.58 ,  0.69 , 10.8  ],
       [ 9.5  ,  0.37 ,  0.52 , ...,  3.29 ,  0.58 , 11.1  ],
       ...,
       [ 7.4  ,  0.55 ,  0.19 , ...,  3.49 ,  0.68 , 10.5  ],
       [ 8.6  ,  0.49 ,  0.28 , ...,  2.93 ,  1.95 ,  9.9  ],
       [ 6.9  ,  0.63 ,  0.33 , ...,  3.22 ,  0.56 ,  9.5  ]])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ntrain = y_train.reshape(len(y_train), 1)
ntest = y_test.reshape(len(y_test), 1)

In [ ]:
ntrain

array([[6],
       [7],
       [6],
       ...,
       [5],
       [6],
       [5]])

In [ ]:

ntest

array([[5],
       [5],
       [5],
       [5],
       [6],
       [6],
       [6],
       [6],
       [7],
       [5],
       [6],
       [5],
       [6],
       [6],
       [6],
       [6],
       [7],
       [5],
       [6],
       [6],
       [6],
       [6],
       [4],
       [6],
       [5],
       [7],
       [6],
       [7],
       [6],
       [6],
       [5],
       [7],
       [7],
       [5],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [5],
       [5],
       [6],
       [6],
       [5],
       [5],
       [6],
       [5],
       [5],
       [7],
       [6],
       [5],
       [6],
       [6],
       [6],
       [5],
       [5],
       [7],
       [5],
       [5],
       [5],
       [6],
       [7],
       [7],
       [5],
       [4],
       [5],
       [6],
       [5],
       [7],
       [5],
       [6],
       [5],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [7],
       [5],
    

In [ ]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [ ]:
xn_train = x_sc.fit_transform(x_train)
yn_train = y_sc.fit_transform(ntrain)

In [ ]:
xn_test = x_sc.transform(x_test)
yn_test = y_sc.transform(ntest)

In [ ]:
xn_train

array([[-2.08620228,  0.38886649, -0.50796368, ...,  3.47303948,
        -0.3261045 ,  2.33995355],
       [-0.5158892 ,  0.58292043, -0.86617089, ...,  1.72681088,
         0.19699875,  0.36359652],
       [ 0.70546541, -0.8863451 ,  1.2830724 , ..., -0.14876798,
        -0.44234967,  0.64593324],
       ...,
       [-0.5158892 ,  0.11164658, -0.40561876, ...,  1.14473469,
         0.13887617,  0.0812598 ],
       [ 0.18202772, -0.22101731,  0.05493337, ..., -2.47707277,
         7.52044432, -0.48341364],
       [-0.80668792,  0.55519844,  0.31079567, ..., -0.60149391,
        -0.55859484, -0.8598626 ]])

In [ ]:
xn_test

array([[-0.98116715,  0.94330631, -0.96851581, ...,  0.82135902,
        -0.44234967, -0.20107692],
       [-0.45772946, -0.60912519,  0.25962321, ..., -0.47214364,
        -1.25606585, -0.01285244],
       [ 0.29834721,  0.61064242, -0.50796368, ..., -0.53681878,
        -0.67484001, -0.76575036],
       ...,
       [-0.45772946,  0.38886649,  0.25962321, ...,  0.88603415,
        -0.20985934, -0.8598626 ],
       [ 0.76362516, -0.16557333,  0.46431305, ..., -0.86019444,
         0.13887617,  0.45770876],
       [ 1.7523408 ,  0.49975445,  2.05065929, ..., -0.60149391,
         0.19699875,  2.81051475]])

In [ ]:
yn_train

array([[ 0.47046932],
       [ 1.72407403],
       [ 0.47046932],
       ...,
       [-0.78313539],
       [ 0.47046932],
       [-0.78313539]])

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [ ]:
x_pol = PolynomialFeatures(degree=1)
x_pol = x_pol.fit_transform(xn_train)

In [ ]:
temp = PolynomialFeatures(degree=1)
temp = temp.fit_transform(xn_test)

In [ ]:
r_reg.fit(xn_train, yn_train)
l_reg.fit(xn_train, yn_train)
d_reg.fit(xn_train, yn_train)
s_reg.fit(xn_train, yn_train)
p_reg.fit(x_pol, yn_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
r_pred = r_reg.predict(xn_test)
l_pred = l_reg.predict(xn_test)
d_pred = d_reg.predict(xn_test)
s_pred = s_reg.predict(xn_test)
p_pred = p_reg.predict(temp)

In [ ]:

from sklearn.metrics import r2_score

In [ ]:
r = r2_score(yn_test, r_pred)
l = r2_score(yn_test, l_pred)
d = r2_score(yn_test, d_pred)
s = r2_score(yn_test, s_pred)
p = r2_score(yn_test, p_pred)

In [ ]:
print(r, l, d, s, p)

0.5560503324358481 0.4260306588792414 0.07247650969833508 0.48933386090306696 0.42603065887924163
